name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download SSH Client
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/win32-openssh" -OutFile "OpenSSH.zip"
        Expand-Archive OpenSSH.zip -DestinationPath "C:\Program Files\OpenSSH"

    - name: Set up SSH
      run: |
        $env:Path += ";C:\Program Files\OpenSSH"
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        Start-Service sshd

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create TCP Tunnel
      run: |
        ssh -p 443 -R 0:localhost:8000 tcp@a.pinggy.io
